version: "3.1"

services:
  app:
    image: ${APPLICATION_IMAGE}
    container_name: ${APPLICATION_NAME}
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime
  master-db:
    image: ${DB_IMAGE}
    container_name: ${MASTER_DB_NAME}
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ${LOCAL_MASTER_REPOSITORY_PATH}:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root1234!
  slave-db:
    image: ${DB_IMAGE}
    container_name: ${SLAVE_DB_NAME}
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ${LOCAL_SLAVE_REPOSITORY_PATH}:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root1234!